name 'cis-hardening'
maintainer 'Schuberg Philis'
maintainer_email 'mdebruin@schubergphilis.com'
license 'Apache-2.0'
description 'Installs/Configures cis-hardening'
version '0.1.0'
chef_version '>= 16.0'
